from __future__ import annotations

from app.agents.enterprise_data_agent import read_bitable
from app.services.audit_service import write_audit_log
from app.services.auth_service import issue_delegated_token


def generate_report(user_id: str) -> dict:
    delegated = issue_delegated_token(
        caller_agent="doc-agent",
        target_agent="enterprise-data-agent",
        delegated_user=user_id,
        resource="bitable",
        action="read",
        task_name="generate_report",
        trace_id=None,
        parent_jti=None,
    )
    data = read_bitable(delegated["access_token"])
    report_body = (
        "Quarterly sales report generated by doc-agent. "
        f"Rows fetched: {len(data['rows'])}. "
        f"Latest revenue snapshot: {data['rows'][-1]['revenue']}."
    )

    write_audit_log(
        trace_id=delegated["trace_id"],
        token_jti=delegated["jti"],
        parent_jti=None,
        caller_agent="doc-agent",
        target_agent="doc-agent",
        delegated_user=user_id,
        resource="document",
        action="write",
        decision="allow",
        reason_code="OK",
        reason_detail="Report assembled and written by doc-agent.",
    )

    return {
        "trace_id": delegated["trace_id"],
        "report": report_body,
        "data_rows": data["rows"],
    }
