from __future__ import annotations

from app.agents.enterprise_data_agent import read_bitable
from app.core.errors import ERRORS
from app.services.audit_service import write_audit_log
from app.services.auth_service import issue_delegated_token


DEFAULT_TASK_HOUR = 10


def issue_enterprise_read_token(
    user_id: str,
    *,
    task_name: str,
    purpose: str = "quarterly_reporting",
    current_hour: int = DEFAULT_TASK_HOUR,
) -> dict:
    return issue_delegated_token(
        caller_agent="doc-agent",
        target_agent="enterprise-data-agent",
        delegated_user=user_id,
        resource="bitable",
        action="read",
        task_name=task_name,
        purpose=purpose,
        current_hour=current_hour,
        trace_id=None,
        parent_jti=None,
    )


def generate_report(user_id: str) -> dict:
    delegated = issue_enterprise_read_token(user_id, task_name="generate_report")
    data = read_bitable(delegated["access_token"])
    report_body = (
        "Quarterly sales report generated by doc-agent. "
        f"Rows fetched: {len(data['rows'])}. "
        f"Latest revenue snapshot: {data['rows'][-1]['revenue']}."
    )

    write_audit_log(
        trace_id=delegated["trace_id"],
        token_jti=delegated["jti"],
        parent_jti=None,
        caller_agent="doc-agent",
        target_agent="doc-agent",
        delegated_user=user_id,
        resource="document",
        action="write",
        decision="allow",
        reason_code="OK",
        reason_detail="Report assembled and written by doc-agent.",
    )

    return {
        "trace_id": delegated["trace_id"],
        "report": report_body,
        "data_rows": data["rows"],
    }


def generate_report_with_fallback(user_id: str) -> dict:
    delegated = issue_enterprise_read_token(
        user_id,
        task_name="generate_report_with_fallback",
        purpose="resilience_drill",
    )

    try:
        data = read_bitable(delegated["access_token"], simulate_timeout=True)
    except ValueError as error:
        if str(error) != "AGENT_002":
            raise

        error_definition = ERRORS["AGENT_002"]
        report_body = (
            "Quarterly sales report generated in degraded mode by doc-agent. "
            "Enterprise data fetch timed out, so the report contains a fallback notice only."
        )

        write_audit_log(
            trace_id=delegated["trace_id"],
            token_jti=delegated["jti"],
            parent_jti=None,
            caller_agent="doc-agent",
            target_agent="doc-agent",
            delegated_user=user_id,
            resource="document",
            action="write",
            decision="allow",
            reason_code="AGENT_002",
            reason_detail="Doc agent returned a degraded report after downstream timeout.",
        )

        return {
            "trace_id": delegated["trace_id"],
            "status": "degraded",
            "report": report_body,
            "data_rows": [],
            "fallback_used": True,
            "upstream_error": {
                "code": error_definition.code,
                "message": error_definition.message,
            },
        }

    return {
        "trace_id": delegated["trace_id"],
        "status": "ok",
        "report": (
            "Quarterly sales report generated by doc-agent. "
            f"Rows fetched: {len(data['rows'])}. "
            f"Latest revenue snapshot: {data['rows'][-1]['revenue']}."
        ),
        "data_rows": data["rows"],
        "fallback_used": False,
        "upstream_error": None,
    }


def generate_report_with_unavailable_dependency(user_id: str) -> dict:
    delegated = issue_enterprise_read_token(
        user_id,
        task_name="availability_probe",
        purpose="availability_probe",
    )

    try:
        read_bitable(delegated["access_token"], failure_mode="unavailable")
    except ValueError as error:
        if str(error) != "AGENT_001":
            raise

        write_audit_log(
            trace_id=delegated["trace_id"],
            token_jti=delegated["jti"],
            parent_jti=None,
            caller_agent="doc-agent",
            target_agent="doc-agent",
            delegated_user=user_id,
            resource="report",
            action="generate",
            decision="deny",
            reason_code="AGENT_001",
            reason_detail="Doc agent aborted report generation because enterprise-data-agent was unavailable.",
        )
        raise

    return {"status": "unexpected"}
